---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: present
  - name: Install our static html file
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: Start and enable Nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
  - name: test Page
    command: curl "{{ ansible_default_ipv4.address }}"
    register: pageOut
  - name: Print webpage
    debug:
      msg: "{{ pageOut.stdout }}"
